name: Import data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 0' # Run every Sunday at 9am UTC

jobs:
  run-script:
    runs-on: ubuntu-latest 

    env:
      HINDSIGHT_PAT_TOKEN: ${{ secrets.HINDSIGHT_PAT_TOKEN }}
    steps:
      - uses: actions/checkout@v2 

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" 

      - name: Install pygithub
        run: |
          python -m pip install pygithub

      - name: Run import script
        run: |
          python import_data_to_readme.py

      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'plots'
          message: 'update hindsight data from remote'
          default_author: github_actions
